apiVersion : apps/v1
kind: Deployment
metadata:
  name: edisonsupipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edisonsupipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: edisonsupipelinesjavascriptdocker 
    spec:
      containers:
        - name: edisonsupipelinesjavascriptdocker 
          image: containerregistryedison.azurecr.io/edisonsupipelinesjavascriptdocker
          ports:
          - containerPort: 8080